[project]
name = "metatensor-lj-test"
description = "Package for testing metatensor model integration"
version = "0.0.0"
dependencies = [
    "torch >=1.12",
    "metatensor-torch >0.4.0-pre,<0.5.0"
]

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "wheel",
    "torch >=1.12"
]
